title: カーボンテック・ジャーニー (Co2TJ)
subtitle: 地方の自然を都会のDXで支援して日本を豊かにしよう
# 二地域居住を推進して地方と都会の対等な関係構築を通して日本を豊かにするプロジェクト
email: mkoikawa@tonoi.co.jp
description: >- # this means to ignore newlines until "baseurl:"
  農家、林業、漁業などの地方生産者のDX化を、ご縁のある都会在住者が支援をして、カーボンクレジット獲得を目指します。
baseurl: "tonoi/Co2TJ" # the subpath of your site, e.g. /blog
url: "https://tonoi.github.io"
# twitter_username: tonoi
github_username: tonoi co,.Ltd.
repository: tonoi/Co2TJ
google_analytics: G-0S9JVP8FB6
show_downloads: false

lang: ja

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

header_pages:
  - index.md
  - about.md
  - service.md
  - contact.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - README.md
  - LICENSE
  - .gitignore
  - .gitmodules
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .DS_Store
  - .vscode/
  - .vscode/settings.json
  - .vscode/tasks.json
  - .vscode/launch.json

sass:
  sass.dir: _sass
  style: compressed

env:
  PAGES_REPO_NWO: tonoi/Co2TJ

