title: カーボンテック・ジャーニー (Co2TJ)
subtitle: 地方の自然を都会のDXで支援して日本を豊かにしよう
# 二地域居住を推進して地方と都会の対等な関係構築を通して日本を豊かにするプロジェクト
email: mkoikawa@tonoi.co.jp
description: >- # this means to ignore newlines until "baseurl:"
  地方の農業・林業・水産業などの豊かな里山を活かすには、広範囲なDX化が必要です。
  そして、都会には地方に移住はできないけどリモートで地方を応援したい人が沢山います。
  そこで、生成AIの力を借りて都会の人たちが地方産業のDX化を支援できる関係を作っていきたいと思います。
  やみくもにDX化と言ってもイメージがわかないので、まずは地方産業の様々な活動を数値化して
  カーボンクレジットとして申請する事で現金収入につなげたいと思います。
baseurl: "/Co2TJ" # the subpath of your site, e.g. /blog
url: "https://tonoi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tonoi
github_username: tonoi
repository: tonoi/Co2TJ
google_analytics: G-0S9JVP8FB6

lang: ja

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
  - README.md
  - LICENSE
  - .gitignore
  - .gitmodules
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .DS_Store
  - .vscode/
  - .vscode/settings.json
  - .vscode/tasks.json
  - .vscode/launch.json

sass:
  sass.dir: .sass

env:
  PAGES_REPO_NWO: tonoi/Co2TJ

header_pages:
  - about.md
  - contact.md
  - projects.md
  - publications.md
  - talks.md
  - teaching.md
